name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fr.PNG
    - assets/tu.PNG
    - assets/hi.jpg
    - assets/i1.PNG
    - assets/i2.PNG
    - assets/i3.PNG
    - assets/i4.PNG
    - assets/i5.PNG
    - assets/i6.PNG
    - assets/i7.PNG
    - assets/i8.PNG
    - assets/i11.PNG
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf